### PR TITLE
update to angular 14

### PR DESCRIPTION
**Pull request by johnmckay-reward**
Have updated the library to support Angular 14, have also updated Jest

https://github.com/thekip/angular-cc-library/issues/109

### CODE REVIEW

**Comment by johnmckay-reward** [comment]
image

**Comment by thekip** [comment]
Thanks for PR, I think, is it possible to support 13 & 14 versions simultaneously? 

Because there no changes in the code, and no big changes in the compiler, probably it's just matter of adding both of this versions to this lib package.json

**Comment by johnmckay-reward** [comment]
It looks like it https://stackoverflow.com/a/47310882/969613

I'll update the PR here, thanks!

**Comment by johnmckay-reward** [comment]
Have updated the PR based on this StackOverflow answer -> https://stackoverflow.com/a/60828558/969613

Thanks

**Comment by johnmckay-reward** [comment]
No worries :)

**Pull request merged**
