### PR TITLE
chore: updated to angular 18

### PR DESCRIPTION
**Pull request by s-torrisi**

### CODE REVIEW

**Comment by thekip** [comment]
Could you please revert all changes related to yarn.lock / package.lock and yarn itself. This project uses yarn as package manager. You don't need to install packages in `projects/angular-cc-library` folder. The package.json file there used only for publishing.

**Comment by s-torrisi** [comment]
> Could you please revert all changes related to yarn.lock / package.lock and yarn itself. This project uses yarn as package manager. You don't need to install packages in `projects/angular-cc-library` folder. The package.json file there used only for publishing.

I kept the yarn.lock in the general project as it is, however i had to change yarn version to 1.22.22 due to a bug regarding the require function not working in tests files

**Comment by thekip** [comment]
Interesting, don't have an idea how yarn could affect tests. Anyway updating a version is a good thing. 

PS

The package manager configuration now could be switched from yarn's approach to node's corepack. It could be done in a separate PR.

**Comment by cwithhart** [comment]
Ok thanks guys for jumping on this! I tried to upgrade Yarn also but wasnt exactly sure what I was doing and it didnt seem to work. 
@s-torrisi - Is there anything you need from me to move forward? Looks like you merged it back into the main branch and all is good? 
Also, will it auto kick off the a new NPM? Or is there another step needed. Thanks again everyone!

**Comment by s-torrisi** [comment]
@cwithhart it looks like the npm publish command on the automatic github actions failed, i think that @thekip needs to take a at it and after that it should be online on NPM

https://github.com/thekip/angular-cc-library/actions/runs/10703285053

**Comment by cwithhart** [comment]
Yea i just noticed the release failed. Thanks for the update!

**Pull request merged**
