### PR TITLE
chore: updating to angular 17

### PR DESCRIPTION
**Pull request by s-torrisi**
first time forking and updating an open source library, hope i didn't mess anything up!

### CODE REVIEW

**Comment by thekip** [comment]
does library generated with angular 17 completely incompatible with angular 16? I mean, may be we should just expand compatiblity range instead of setting strict angular 17 peer dependency?

**Comment by s-torrisi** [comment]
Didn't think of that
I tried expanding compatibility range to 16 and tried to use the library via yarn link in my project, the library only worked on angular 17, with version 16 it got runtime errors

**Comment by s-torrisi** [comment]
I did try the library in angular 16 but it gives me errors, i did also find some errors while trying to use the library on my project
I did not yet localize the errors, they could be on my side only caused by the updates.

I will try to run more tests and follow up with more info

**Comment by s-torrisi** [comment]
Ok, it looks like i got the problem because npm link generates an injection error for some obscure reason.
The library is working on angular 17, everything should be good to go

**Comment by thekip** [comment]
I updated version as well as other tools and also added support of standalone directives https://github.com/thekip/angular-cc-library/pull/123

**Comment by thekip** [comment]
The new version v3.3.0 is released

**Pull request closed without merging**
